package springboot.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import springboot.modal.vo.ContentVo;
import springboot.modal.vo.ContentVoExample;

public interface ContentVoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_contents
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    long countByExample(ContentVoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_contents
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    int deleteByExample(ContentVoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_contents
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    int deleteByPrimaryKey(Integer cid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_contents
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    int insert(ContentVo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_contents
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    int insertSelective(ContentVo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_contents
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    List<ContentVo> selectByExampleWithBLOBs(ContentVoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_contents
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    List<ContentVo> selectByExample(ContentVoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_contents
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    ContentVo selectByPrimaryKey(Integer cid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_contents
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    int updateByExampleSelective(@Param("record") ContentVo record, @Param("example") ContentVoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_contents
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") ContentVo record, @Param("example") ContentVoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_contents
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    int updateByExample(@Param("record") ContentVo record, @Param("example") ContentVoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_contents
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    int updateByPrimaryKeySelective(ContentVo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_contents
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(ContentVo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_contents
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    int updateByPrimaryKey(ContentVo record);
}