package springboot.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import springboot.modal.vo.LogVo;
import springboot.modal.vo.LogVoExample;

public interface LogVoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_logs
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    long countByExample(LogVoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_logs
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    int deleteByExample(LogVoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_logs
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_logs
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    int insert(LogVo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_logs
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    int insertSelective(LogVo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_logs
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    List<LogVo> selectByExample(LogVoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_logs
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    LogVo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_logs
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    int updateByExampleSelective(@Param("record") LogVo record, @Param("example") LogVoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_logs
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    int updateByExample(@Param("record") LogVo record, @Param("example") LogVoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_logs
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    int updateByPrimaryKeySelective(LogVo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_logs
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    int updateByPrimaryKey(LogVo record);
}