package springboot.dao;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;
import springboot.dto.MetaDto;
import springboot.modal.vo.MetasVo;
import springboot.modal.vo.MetasVoExample;
@Component
public interface MetasVoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_metas
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    long countByExample(MetasVoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_metas
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    int deleteByExample(MetasVoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_metas
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    int deleteByPrimaryKey(Integer mid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_metas
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    int insert(MetasVo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_metas
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    int insertSelective(MetasVo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_metas
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    List<MetasVo> selectByExample(MetasVoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_metas
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    MetasVo selectByPrimaryKey(Integer mid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_metas
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    int updateByExampleSelective(@Param("record") MetasVo record, @Param("example") MetasVoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_metas
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    int updateByExample(@Param("record") MetasVo record, @Param("example") MetasVoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_metas
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    int updateByPrimaryKeySelective(MetasVo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_metas
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    int updateByPrimaryKey(MetasVo record);


    List<MetaDto> selectFromSql(Map<String, Object> paraMap);

    MetaDto selectDtoByNameAndType(@Param("name") String name, @Param("type") String type);

    Integer countWithSql(Integer mid);

}