package springboot.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;
import springboot.modal.vo.RelationShipVoExample;
import springboot.modal.vo.RelationShipVoKey;
@Component
public interface RelationShipVoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_relationships
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    long countByExample(RelationShipVoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_relationships
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    int deleteByExample(RelationShipVoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_relationships
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    int deleteByPrimaryKey(RelationShipVoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_relationships
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    int insert(RelationShipVoKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_relationships
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    int insertSelective(RelationShipVoKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_relationships
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    List<RelationShipVoKey> selectByExample(RelationShipVoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_relationships
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    int updateByExampleSelective(@Param("record") RelationShipVoKey record, @Param("example") RelationShipVoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_relationships
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    int updateByExample(@Param("record") RelationShipVoKey record, @Param("example") RelationShipVoExample example);
}