package springboot.modal.vo;

public class CommentVo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comments.coid
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    private Integer coid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comments.cid
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    private Integer cid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comments.created
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    private Integer created;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comments.author
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    private String author;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comments.author_id
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    private Integer authorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comments.owner_id
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    private Integer ownerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comments.mail
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    private String mail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comments.url
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comments.ip
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    private String ip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comments.agent
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    private String agent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comments.type
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comments.status
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comments.parent
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    private Integer parent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comments.content
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comments.coid
     *
     * @return the value of t_comments.coid
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    public Integer getCoid() {
        return coid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comments.coid
     *
     * @param coid the value for t_comments.coid
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    public void setCoid(Integer coid) {
        this.coid = coid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comments.cid
     *
     * @return the value of t_comments.cid
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comments.cid
     *
     * @param cid the value for t_comments.cid
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comments.created
     *
     * @return the value of t_comments.created
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    public Integer getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comments.created
     *
     * @param created the value for t_comments.created
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    public void setCreated(Integer created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comments.author
     *
     * @return the value of t_comments.author
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comments.author
     *
     * @param author the value for t_comments.author
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    public void setAuthor(String author) {
        this.author = author == null ? null : author.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comments.author_id
     *
     * @return the value of t_comments.author_id
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    public Integer getAuthorId() {
        return authorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comments.author_id
     *
     * @param authorId the value for t_comments.author_id
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    public void setAuthorId(Integer authorId) {
        this.authorId = authorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comments.owner_id
     *
     * @return the value of t_comments.owner_id
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    public Integer getOwnerId() {
        return ownerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comments.owner_id
     *
     * @param ownerId the value for t_comments.owner_id
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    public void setOwnerId(Integer ownerId) {
        this.ownerId = ownerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comments.mail
     *
     * @return the value of t_comments.mail
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    public String getMail() {
        return mail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comments.mail
     *
     * @param mail the value for t_comments.mail
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    public void setMail(String mail) {
        this.mail = mail == null ? null : mail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comments.url
     *
     * @return the value of t_comments.url
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comments.url
     *
     * @param url the value for t_comments.url
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comments.ip
     *
     * @return the value of t_comments.ip
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comments.ip
     *
     * @param ip the value for t_comments.ip
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comments.agent
     *
     * @return the value of t_comments.agent
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    public String getAgent() {
        return agent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comments.agent
     *
     * @param agent the value for t_comments.agent
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    public void setAgent(String agent) {
        this.agent = agent == null ? null : agent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comments.type
     *
     * @return the value of t_comments.type
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comments.type
     *
     * @param type the value for t_comments.type
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comments.status
     *
     * @return the value of t_comments.status
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comments.status
     *
     * @param status the value for t_comments.status
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comments.parent
     *
     * @return the value of t_comments.parent
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    public Integer getParent() {
        return parent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comments.parent
     *
     * @param parent the value for t_comments.parent
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    public void setParent(Integer parent) {
        this.parent = parent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comments.content
     *
     * @return the value of t_comments.content
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comments.content
     *
     * @param content the value for t_comments.content
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}