package springboot.modal.vo;

public class LogVo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_logs.id
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_logs.action
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    private String action;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_logs.data
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    private String data;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_logs.author_id
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    private Integer authorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_logs.ip
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    private String ip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_logs.created
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    private Integer created;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_logs.id
     *
     * @return the value of t_logs.id
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_logs.id
     *
     * @param id the value for t_logs.id
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_logs.action
     *
     * @return the value of t_logs.action
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    public String getAction() {
        return action;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_logs.action
     *
     * @param action the value for t_logs.action
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    public void setAction(String action) {
        this.action = action == null ? null : action.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_logs.data
     *
     * @return the value of t_logs.data
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    public String getData() {
        return data;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_logs.data
     *
     * @param data the value for t_logs.data
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    public void setData(String data) {
        this.data = data == null ? null : data.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_logs.author_id
     *
     * @return the value of t_logs.author_id
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    public Integer getAuthorId() {
        return authorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_logs.author_id
     *
     * @param authorId the value for t_logs.author_id
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    public void setAuthorId(Integer authorId) {
        this.authorId = authorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_logs.ip
     *
     * @return the value of t_logs.ip
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_logs.ip
     *
     * @param ip the value for t_logs.ip
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_logs.created
     *
     * @return the value of t_logs.created
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    public Integer getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_logs.created
     *
     * @param created the value for t_logs.created
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    public void setCreated(Integer created) {
        this.created = created;
    }
}