package springboot.modal.vo;

public class MetasVo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_metas.mid
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    private Integer mid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_metas.name
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_metas.slug
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    private String slug;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_metas.type
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_metas.description
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_metas.sort
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    private Integer sort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_metas.parent
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    private Integer parent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_metas.mid
     *
     * @return the value of t_metas.mid
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    public Integer getMid() {
        return mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_metas.mid
     *
     * @param mid the value for t_metas.mid
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    public void setMid(Integer mid) {
        this.mid = mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_metas.name
     *
     * @return the value of t_metas.name
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_metas.name
     *
     * @param name the value for t_metas.name
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_metas.slug
     *
     * @return the value of t_metas.slug
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    public String getSlug() {
        return slug;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_metas.slug
     *
     * @param slug the value for t_metas.slug
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    public void setSlug(String slug) {
        this.slug = slug == null ? null : slug.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_metas.type
     *
     * @return the value of t_metas.type
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_metas.type
     *
     * @param type the value for t_metas.type
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_metas.description
     *
     * @return the value of t_metas.description
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_metas.description
     *
     * @param description the value for t_metas.description
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_metas.sort
     *
     * @return the value of t_metas.sort
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_metas.sort
     *
     * @param sort the value for t_metas.sort
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_metas.parent
     *
     * @return the value of t_metas.parent
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    public Integer getParent() {
        return parent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_metas.parent
     *
     * @param parent the value for t_metas.parent
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    public void setParent(Integer parent) {
        this.parent = parent;
    }
}