package springboot.modal.vo;

public class OptionVo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_options.name
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_options.value
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    private String value;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_options.description
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_options.name
     *
     * @return the value of t_options.name
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_options.name
     *
     * @param name the value for t_options.name
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_options.value
     *
     * @return the value of t_options.value
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_options.value
     *
     * @param value the value for t_options.value
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_options.description
     *
     * @return the value of t_options.description
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_options.description
     *
     * @param description the value for t_options.description
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}