package springboot.modal.vo;

public class RelationShipVoKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_relationships.cid
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    private Integer cid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_relationships.mid
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    private Integer mid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_relationships.cid
     *
     * @return the value of t_relationships.cid
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_relationships.cid
     *
     * @param cid the value for t_relationships.cid
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_relationships.mid
     *
     * @return the value of t_relationships.mid
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    public Integer getMid() {
        return mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_relationships.mid
     *
     * @param mid the value for t_relationships.mid
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    public void setMid(Integer mid) {
        this.mid = mid;
    }
}