package springboot.modal.vo;

public class UserVo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users.uid
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users.username
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users.password
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users.email
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users.home_url
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    private String homeUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users.screen_name
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    private String screenName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users.created
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    private Integer created;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users.activated
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    private Integer activated;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users.logged
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    private Integer logged;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users.group_name
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    private String groupName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users.uid
     *
     * @return the value of t_users.uid
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users.uid
     *
     * @param uid the value for t_users.uid
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users.username
     *
     * @return the value of t_users.username
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users.username
     *
     * @param username the value for t_users.username
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users.password
     *
     * @return the value of t_users.password
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users.password
     *
     * @param password the value for t_users.password
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users.email
     *
     * @return the value of t_users.email
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users.email
     *
     * @param email the value for t_users.email
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users.home_url
     *
     * @return the value of t_users.home_url
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    public String getHomeUrl() {
        return homeUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users.home_url
     *
     * @param homeUrl the value for t_users.home_url
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    public void setHomeUrl(String homeUrl) {
        this.homeUrl = homeUrl == null ? null : homeUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users.screen_name
     *
     * @return the value of t_users.screen_name
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    public String getScreenName() {
        return screenName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users.screen_name
     *
     * @param screenName the value for t_users.screen_name
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    public void setScreenName(String screenName) {
        this.screenName = screenName == null ? null : screenName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users.created
     *
     * @return the value of t_users.created
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    public Integer getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users.created
     *
     * @param created the value for t_users.created
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    public void setCreated(Integer created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users.activated
     *
     * @return the value of t_users.activated
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    public Integer getActivated() {
        return activated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users.activated
     *
     * @param activated the value for t_users.activated
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    public void setActivated(Integer activated) {
        this.activated = activated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users.logged
     *
     * @return the value of t_users.logged
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    public Integer getLogged() {
        return logged;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users.logged
     *
     * @param logged the value for t_users.logged
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    public void setLogged(Integer logged) {
        this.logged = logged;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users.group_name
     *
     * @return the value of t_users.group_name
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    public String getGroupName() {
        return groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users.group_name
     *
     * @param groupName the value for t_users.group_name
     *
     * @mbg.generated Thu Nov 08 10:42:29 CST 2018
     */
    public void setGroupName(String groupName) {
        this.groupName = groupName == null ? null : groupName.trim();
    }

    @Override
    public String toString() {
        return "UserVo{" +
                "uid=" + uid +
                ", username='" + username + '\'' +
                ", password='" + password + '\'' +
                ", email='" + email + '\'' +
                ", homeUrl='" + homeUrl + '\'' +
                ", screenName='" + screenName + '\'' +
                ", created=" + created +
                ", activated=" + activated +
                ", logged=" + logged +
                ", groupName='" + groupName + '\'' +
                '}';
    }
}