server:
  port: 8090

spring:
  profiles:
    active: dev

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/myblogdb?useSSL=false
    username: root
    password: 111111
    driver-class-name: com.mysql.jdbc.Driver
    max-idle: 10
    max-wait: 10000
    min-idle: 5
    initial-size: 5


mybatis:
  type-aliases-package: com.springboot.dao
  mapper-locations: classpath:mapper/*.xml





